name: sample_pubspec
description: A sample mqtt web application
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  mqtt:
    path: ../../

dev_dependencies:
  build_runner: ^0.10.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
